import {CONCEPTS,AAC,ACTIVITY_SETS,COACH_ROUTINES,LESSONS,HELP,ROUTINES,NO_MATERIALS,HANDBOOK} from './data.js';import {load,save,clearAll} from './storage.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];const main=$('#main'),modal=$('#modal'),mb=$('#modalBody');const concept=Object.fromEntries(CONCEPTS.map(x=>[x.id,x]));function integrityAudit(){const ids=new Set(CONCEPTS.map(x=>x.id)),issues=[];if(ids.size!==CONCEPTS.length)issues.push('Duplicate concept IDs');for(const a of ACTIVITY_SETS){if(!a.sets?.length)issues.push('Empty activity '+a.id);for(const [t,cs] of (a.sets||[])){if(!ids.has(t))issues.push('Missing target '+t+' in '+a.id);for(const c of cs)if(!ids.has(c))issues.push('Missing choice '+c+' in '+a.id)}}for(const a of AAC)if(a.img&&!ids.has(a.img))issues.push('Missing AAC concept '+a.img);return issues}const integrityIssues=integrityAudit();if(integrityIssues.length)console.error('WAPS integrity audit failed',integrityIssues);
const fresh=()=>({schema:2,profiles:[],active:null,settings:{reduced:false,lowStim:false,grid:4,academyDone:[],childMode:false},sessions:[],observations:[],customAAC:[],goals:[],supports:[]});let S=(await load())||fresh();if(!S.schema||S.schema<2)S=fresh();const persist=async()=>save(S);const active=()=>S.profiles.find(p=>p.id===S.active)||null;const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const now=()=>new Date().toISOString();let HIGHRES_MANIFEST={};try{let r=await fetch('./assets/concepts/highres/manifest.json',{cache:'no-store'});if(r.ok)HIGHRES_MANIFEST=await r.json()}catch{}const HIGHRES_CONCEPTS=new Set(Object.keys(HIGHRES_MANIFEST));function visualHTML(id,cls=''){let c=concept[id];if(!c)return '';if(HIGHRES_CONCEPTS.has(id))return `<span class="concept-hi ${cls}" role="img" aria-label="${esc(c.label)}"><img src="./assets/concepts/highres/${id}.webp" alt="${esc(c.label)}" loading="lazy" decoding="async" onerror="this.onerror=null;this.src='${c.image}'"></span>`;return `<img class="${cls} concept-fallback" src="${c.image}" alt="${esc(c.label)}" loading="lazy" decoding="async">`;}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}function show(html){mb.innerHTML=html;modal.showModal()}function route(){return location.hash.slice(1)||'home'}function go(r){if(route()===r){render()}else{location.hash=r}}function nav(){
  $$('.bottomnav button,.desktopnav button').forEach(b=>b.classList.toggle('active',b.dataset.route===route()));
  let p=active(),c=$('#childSwitcher');
  if(c)c.innerHTML=p?`<span class="child-avatar">${p.photo?`<img class="child-avatar-img" src="${p.photo}" alt="">`:(p.name||'?').slice(0,1).toUpperCase()}</span><span><b>${esc(p.name)}</b><small>My profile</small></span><span>⌄</span>`:'<b>Set up child</b>';
  if(c)c.onclick=e=>{e.preventDefault();e.stopPropagation();profileModal()};
}
function shell(title,lead,body){return `<div class="page-stage"><div class="section-head"><div><div class="eyebrow">WAPS Communication</div><h1>${title}</h1><p>${lead}</p></div></div>${body}</div>`}
function home(){let p=active(),ss=S.sessions.filter(x=>x.profile===S.active),obs=S.observations.filter(x=>x.profile===S.active),goals=S.goals.filter(x=>x.profile===S.active&&x.active),name=p?esc(p.name):'Your child',goal=goals[0]?esc(goals[0].text):'Choose what matters most',real=obs.filter(x=>x.context==='real-life').length,sp=new Set(obs.filter(x=>x.spontaneous).map(x=>x.purpose)).size;return `<div class="waps-home premium-home">
<section class="home-stage">
  <div class="home-copy">
    <div class="eyebrow">TODAY WITH WAPS</div>
    <h1>${p?`Hi ${name}! Let’s make one communication moment count.`:'Every child has something to say.'}</h1>
    <p>${p?'Pick one simple activity. WAPS will guide you and your child step by step.':'Set up a child profile and WAPS will create a simple starting path using Talk, Practice and Coach.'}</p>
    <div class="home-primary-actions">
      <button class="home-action-card practice-card" data-route="practice"><span class="home-action-icon">★</span><span><b>Practise together</b><small>Short visual learning activity</small></span><i>›</i></button>
      <button class="home-action-card talk-card" data-route="talk"><span class="home-action-icon">●</span><span><b>Open WAPS Talk</b><small>Communicate with pictures and words</small></span><i>›</i></button>
      <button class="home-action-card coach-card-home" data-route="coach"><span class="home-action-icon">●●</span><span><b>Coach me now</b><small>Guide a real interaction</small></span><i>›</i></button>
    </div>
  </div>
  <div class="home-character" aria-hidden="true">
    <div class="character-orbit orbit-one"></div><div class="character-orbit orbit-two"></div>
    <div class="character-face"><span>${p?(p.name||'?').slice(0,1).toUpperCase():'W'}</span></div>
    <div class="character-bubble">I have something to say!</div>
  </div>
</section>
<section class="home-feature-grid">
  <article class="home-feature-card goal-card">
    <div class="feature-badge">🎯</div><div><span class="eyebrow">ACTIVE GOAL</span><h2>${goal}</h2><p>${goals[0]?'Practice and real-life coaching will connect to this goal.':'Choose one useful communication priority.'}</p></div>
    <button class="feature-cta purple" data-action="goals">${goals[0]?'Manage goal':'Choose goal'}</button>
  </article>
  <article class="home-feature-card session-card">
    <div class="feature-badge">✨</div><div><span class="eyebrow">TODAY</span><h2>${p?'Your guided session is ready':'Set up a child profile'}</h2><p>${p?'Connect → model → practise → use it in real life.':'A few friendly questions help WAPS personalise the experience.'}</p></div>
    <button class="feature-cta green" data-action="${p?'today':'profile'}">${p?'Start today':'Get started'}</button>
  </article>
</section>
<section class="home-progress-strip" aria-label="Progress summary">
  <div><span class="progress-icon">★</span><strong>${ss.length}</strong><small>practice sessions</small></div>
  <div><span class="progress-icon">♥</span><strong>${real}</strong><small>real-life moments</small></div>
  <div><span class="progress-icon">↗</span><strong>${sp}</strong><small>spontaneous purposes</small></div>
</section>
<section class="home-tip"><span>💛</span><div><b>WAPS reminder</b><p>Communication can be speech, AAC, pointing, gesture, sign, pictures, typing or another clear intentional response.</p></div></section>
</div>`}
function talk(){let p=active();let cats=['all','core','safety','people','actions','food','places','feelings','body','social','repair','personal'];return `<div class="talk-stage"><div class="talk-title"><div><span class="eyebrow">WAPS COMMUNICATION</span><h1>WAPS Talk</h1><p>Build a message in the way that works best. Important words always stay easy to reach.</p></div><div class="talk-bubble">💬</div></div><div class="aac-toolbar premium-aac"><div class="sentence" id="sentence" aria-live="polite"><span class="mini">Tap a word or picture to build a message…</span></div><div class="aac-actions"><button class="btn speak-big" data-action="speak">🔊 Speak</button><button class="btn ghost" data-action="backspace">⌫ Backspace</button><button class="btn ghost" data-action="clearSentence">Clear</button><button class="btn secondary" data-action="partner">👥 Partner Mode: <span id="partnerState">Off</span></button></div><div id="partnerTip" class="partner hidden"><b>MODEL, DON’T TEST.</b> Touch one or two useful words as you naturally say them. Your child does not need to copy you.</div><div class="catbar">${cats.map((c,i)=>`<button class="chip aac-cat" data-cat="${c}" aria-pressed="${i===0}">${c==='all'?'All':c[0].toUpperCase()+c.slice(1)}</button>`).join('')}</div></div><div class="aac-grid premium-grid" id="aacGrid" style="grid-template-columns:repeat(${S.settings.grid||4},1fr)"></div><div class="aac-bottom"><button class="btn secondary" data-action="customAAC">＋ Add personal word or photo</button>${p?'':`<div class="notice warn">AAC works without a profile. Set up a child when you want personal vocabulary and goals.</div>`}</div></div>`}
let sentence=[],aacCat='all',partner=false;function aacSymbolHTML(x){
 const id=x.id;
 const wrap=(tone,body)=>`<span class="waps-aac-symbol ${tone}" aria-hidden="true"><svg viewBox="0 0 64 64" focusable="false">${body}</svg></span>`;
 const icons={
  yes:['green','<circle cx="32" cy="32" r="25"/><path d="M20 33l8 8 17-20" class="stroke"/>'],
  no:['red','<circle cx="32" cy="32" r="25"/><path d="M22 22l20 20M42 22 22 42" class="stroke"/>'],
  help:['teal','<circle cx="32" cy="32" r="25"/><path d="M24 24c1-8 16-9 17 0 1 7-9 7-9 14" class="stroke"/><circle cx="32" cy="47" r="3" class="dot"/>'],
  stop:['red','<path d="M23 6h18l17 17v18L41 58H23L6 41V23z"/><rect x="18" y="28" width="28" height="8" rx="4" class="white"/>'],
  break:['amber','<rect x="7" y="7" width="50" height="50" rx="15"/><rect x="20" y="19" width="8" height="26" rx="4" class="white"/><rect x="36" y="19" width="8" height="26" rx="4" class="white"/>'],
  more:['blue','<circle cx="32" cy="32" r="25"/><path d="M32 18v28M18 32h28" class="stroke"/>'],
  finished:['green','<circle cx="32" cy="32" r="25"/><path d="M19 33l9 9 18-22" class="stroke"/>'],
  i:['purple','<circle cx="32" cy="22" r="10"/><path d="M16 52c2-14 9-21 16-21s14 7 16 21z"/>'],
  want:['blue','<path d="M9 32h36"/><path d="m36 20 13 12-13 12" class="stroke"/>'],
  like:['pink','<path d="M32 52 11 31C1 20 17 8 27 18l5 6 5-6c10-10 26 2 16 13z"/>'],
  dontlike:['red','<path d="M32 52 11 31C1 20 17 8 27 18l5 6 5-6c10-10 26 2 16 13z"/><path d="M14 50 50 14" class="stroke"/>'],
  go:['green','<circle cx="32" cy="32" r="25"/><path d="M18 32h28M37 22l10 10-10 10" class="stroke"/>'],
  scared:['amber','<path d="M32 7 59 55H5z"/><path d="M32 22v17" class="stroke"/><circle cx="32" cy="47" r="3" class="dot"/>'],
  loud:['orange','<path d="M10 27h10l13-11v32L20 37H10z"/><path d="M39 22c6 5 6 15 0 20M46 16c10 9 10 23 0 32" class="stroke"/>'],
  space:['purple','<path d="M8 32h48M18 22 8 32l10 10M46 22l10 10-10 10" class="stroke"/>'],
  understand:['teal','<circle cx="32" cy="32" r="25"/><path d="M23 24c1-8 17-9 18 0 1 7-9 8-9 14" class="stroke"/><circle cx="32" cy="47" r="3" class="dot"/>'],
  again:['blue','<path d="M17 19h23c9 0 14 6 14 13s-5 13-14 13H20" class="stroke"/><path d="m22 11-9 8 9 8" class="stroke"/>'],
  show:['teal','<path d="M7 32c8-12 16-18 25-18s17 6 25 18c-8 12-16 18-25 18S15 44 7 32z"/><circle cx="32" cy="32" r="8" class="white"/>'],
  mind:['purple','<path d="M45 18H25c-10 0-16 6-16 14s6 14 16 14h18" class="stroke"/><path d="m34 37 10 9-10 9" class="stroke"/>'],
  dontknow:['blue','<circle cx="32" cy="32" r="25"/><path d="M23 24c1-8 17-9 18 0 1 7-9 8-9 14" class="stroke"/><circle cx="32" cy="47" r="3" class="dot"/>'],
  notthat:['red','<circle cx="32" cy="32" r="25"/><path d="M21 21l22 22M43 21 21 43" class="stroke"/>'],
  myturn:['purple','<circle cx="32" cy="18" r="8"/><path d="M17 46c2-12 8-18 15-18s13 6 15 18z"/><circle cx="49" cy="47" r="10" class="badge"/><text x="49" y="52" text-anchor="middle" class="num">1</text>'],
  yourturn:['blue','<circle cx="32" cy="18" r="8"/><path d="M17 46c2-12 8-18 15-18s13 6 15 18z"/><circle cx="49" cy="47" r="10" class="badge"/><text x="49" y="52" text-anchor="middle" class="num">2</text>'],
  hello:['green','<path d="M17 48c-5-9-4-18 0-25l5 10V15c0-3 5-3 5 0v14-17c0-3 5-3 5 0v17-14c0-3 5-3 5 0v15-10c0-3 5-3 5 0v17c0 12-7 19-17 19z"/>'],
  goodbye:['orange','<path d="M17 48c-5-9-4-18 0-25l5 10V15c0-3 5-3 5 0v14-17c0-3 5-3 5 0v17-14c0-3 5-3 5 0v15-10c0-3 5-3 5 0v17c0 12-7 19-17 19z"/><path d="M44 13h13M52 7l6 6-6 6" class="stroke"/>']
 };
 const v=icons[id];if(v)return wrap(v[0],v[1]);if(x.img)return visualHTML(x.img,'aac-photo');return `<span class="symbol" aria-hidden="true">${esc(x.symbol||'•')}</span>`;
}
function drawAAC(){let g=$('#aacGrid');if(!g)return;let items=[...AAC,...S.customAAC.filter(x=>!S.active||x.profile===S.active).map(x=>({...x,cat:'personal'}))];if(aacCat!=='all')items=items.filter(x=>x.cat===aacCat);g.innerHTML=items.map(x=>`<button class="aac ${x.cat==='safety'?'safety':''}" data-word="${esc(x.label)}" aria-label="${esc(x.label)}">${x.photo?`<img src="${x.photo}" alt="">`:aacSymbolHTML(x)}<span>${esc(x.label)}</span></button>`).join('')}
function drawSentence(){let el=$('#sentence');if(el)el.innerHTML=sentence.length?sentence.map(x=>`<span class="sentence-word">${esc(x)}</span>`).join(''):'<span class="mini">Tap words to build a message…</span>'}
function practice(){let cards=ACTIVITY_SETS.map((a,i)=>{let sample=a.sets?.[0]?.[0],img=concept[sample]?.image||'book.svg';return `<article class="waps-launch-card practice-launch"><div class="launch-art">${visualHTML(sample,'launch-photo')}</div><div class="eyebrow">${esc(a.domain)}</div><h3>${esc(a.title)}</h3><p>${a.engine==='communicate'?'Practise a useful message in a supportive way.':'Short visual practice followed by real-life use.'}</p><button class="reference-start" data-start="${a.id}">Start activity <span>→</span></button></article>`}).join('');return `<div class="reference-page practice-library"><section class="reference-hero"><div class="hero-icon">★</div><div><span class="eyebrow">PRACTISE TOGETHER</span><h1>Choose something to practise.</h1><p>Short, clear activities. Communication can happen with speech, AAC, pointing, gesture, pictures, signs or another intentional response.</p></div></section><div class="reference-section-title"><h2>Activities</h2><span>${ACTIVITY_SETS.length} ways to practise</span></div><section class="launch-grid">${cards}</section></div>`}
let currentAct=null,currentSet=0;function activity(id){let a=ACTIVITY_SETS.find(x=>x.id===id);currentAct=a;currentSet=Math.floor(Math.random()*a.sets.length);let [target,choices]=a.sets[currentSet],q=a.prompt.replace('{target}',concept[target]?.label.toLowerCase()||target).replace('{TARGET}',(concept[target]?.label||target).toUpperCase());let randomized=[...choices].sort(()=>Math.random()-.5);let isMessage=a.domain==='Self-advocacy'||a.domain==='Communication repair';main.innerHTML=`<div class="activity-shell premium-activity ${isMessage?'message-practice':''}"><div class="activity-breadcrumb"><button class="round-back btn ghost" data-route="practice">←</button><span>${esc(a.domain)}</span><b>›</b><strong>${esc(a.title)}</strong></div><div class="activity-banner"><button class="listen-prompt" data-action="repeatPrompt" aria-label="Hear instruction">🔊</button><div class="prompt">${esc(q)}</div><div class="activity-score" aria-label="Activity progress">⭐ <b>1</b> / 10</div></div><div class="choices">${randomized.map(c=>`<button class="choice ${isMessage?'message-choice':''}" data-choice="${c}" data-target="${target}">${isMessage?`<span class="message-symbol symbol-${c}" aria-hidden="true"></span>`:visualHTML(c,'activity-photo')}<span>${a.engine==='label'?'':esc(concept[c].label)}</span></button>`).join('')}</div><div id="feedback"></div><div class="support-question"><h3>How much help was needed?</h3><div class="support-buttons"><button type="button" class="support-choice active" data-support="Independent">✓ <span>Independent</span></button><button type="button" class="support-choice" data-support="Gesture">✋ <span>Gestural</span></button><button type="button" class="support-choice" data-support="Verbal cue">● <span>Verbal</span></button><button type="button" class="support-choice" data-support="Direct assistance">👥 <span>Full Support</span></button></div><select id="promptLevel" class="visually-hidden" aria-label="How much help was needed?"><option>Independent</option><option>Gesture</option><option>Verbal cue</option><option>Direct assistance</option></select></div><div class="activity-footer"><button class="activity-back btn ghost" data-route="practice">‹ Back</button><button class="activity-repeat btn" data-action="repeatPrompt">🔊 Repeat</button></div></div>`;nav()}
function coach(){let icons=['👀','⏳','💬','🤝','✨','🎯','🌱','💜'];let options=COACH_ROUTINES.map((x,i)=>`<article class="waps-launch-card coach-launch"><div class="coach-art" aria-hidden="true">${icons[i%icons.length]}</div><span class="eyebrow">LIVE COACH</span><h2>${esc(x.title)}</h2><p>WAPS guides you one step at a time while the real interaction happens with your child.</p><button class="reference-start" data-coach="${x.id}">Guide me <span>→</span></button></article>`).join('');return `<div class="reference-page coach-home"><section class="reference-hero coach-hero"><div class="hero-icon blue">👥</div><div><span class="eyebrow">COACH ME</span><h1>Communication grows in everyday moments.</h1><p>Choose a situation and WAPS will show you what to do, what to watch for and when to wait.</p></div></section><section class="launch-grid coach-grid">${options}</section><div class="reference-note"><b>Your child's communication counts.</b><span>Refusal, turning away, AAC, pointing, gesture, signs and speech can all communicate.</span></div></div>`}
let coachRun=null,coachStep=0;function coachScreen(id){coachRun=COACH_ROUTINES.find(x=>x.id===id);coachStep=0;drawCoachStep()}function drawCoachStep(){let s=coachRun.steps[coachStep],isWait=s[0]==='Wait';main.innerHTML=`<div class="coach-wrap"><button class="btn ghost" data-route="coach">← Coach choices</button><div class="coach-card" style="margin-top:14px"><div class="coach-visual" aria-hidden="true">${isWait?'◷':'◎'}</div><div class="eyebrow" style="margin-top:18px">Step ${coachStep+1} of ${coachRun.steps.length}</div><h2>${esc(s[0])}</h2><p>${esc(s[1])}</p>${isWait?'<div class="timer" id="waitTimer">8</div><p class="mini">Eight seconds is only a gentle example—not a universal rule.</p>':''}<div class="actions" style="justify-content:center"><button class="btn ghost" data-action="coachPrev" ${coachStep===0?'disabled':''}>Back</button><button class="btn" data-action="coachNext">${coachStep===coachRun.steps.length-1?'Record interaction':'Next'}</button></div></div></div>`;if(isWait)startTimer();nav()}
let timerId;function startTimer(){clearInterval(timerId);let n=8;timerId=setInterval(()=>{let e=$('#waitTimer');if(!e){clearInterval(timerId);return}n--;e.textContent=Math.max(0,n);if(n<=0)clearInterval(timerId)},1000)}
function progress(){let p=active(),sessions=S.sessions.filter(x=>x.profile===S.active),obs=S.observations.filter(x=>x.profile===S.active),ind=sessions.filter(x=>x.result==='correct'&&x.prompt==='Independent').length,sp=obs.filter(x=>x.spontaneous).length,real=obs.filter(x=>x.context==='real-life').length,total=Math.max(1,sessions.length),indPct=Math.round(ind/total*100);let summary=sessions.length?`${p?.name||'Your child'} has ${sessions.length} recorded practice/coaching session${sessions.length===1?'':'s'}. ${real} real-life communication moment${real===1?' has':'s have'} been recorded, including ${sp} marked as spontaneous.`:'Start with one short practice or Coach Me activity. WAPS will build a simple communication story here.';return `<div class="reference-page progress-page"><section class="reference-hero progress-hero"><div class="hero-icon green">▥</div><div><span class="eyebrow">PROGRESS</span><h1>${p?esc(p.name)+"’s communication story":'Communication story'}</h1><p>Celebrate useful communication in the app and in everyday life—without turning it into a diagnostic score.</p></div></section><section class="story-stats"><article><span class="stat-icon purple">★</span><strong>${sessions.length}</strong><b>Practice moments</b><small>Recorded in WAPS</small></article><article><span class="stat-icon green">✓</span><strong>${indPct}%</strong><b>Independent in practice</b><small>Of recorded practice</small></article><article><span class="stat-icon blue">⌂</span><strong>${real}</strong><b>Real-life moments</b><small>Recorded by caregiver</small></article><article><span class="stat-icon orange">✨</span><strong>${sp}</strong><b>Spontaneous moments</b><small>Recorded by caregiver</small></article></section><section class="progress-story-card"><div class="story-illustration">🌱</div><div><span class="eyebrow">THIS WEEK'S STORY</span><h2>Small moments matter.</h2><p>${esc(summary)}</p><button class="reference-start" data-action="report">Print / save summary <span>→</span></button></div></section><section class="reference-list-card"><h2>Recent real-life communication</h2>${obs.slice(-6).reverse().map(o=>`<div class="story-row"><span class="story-dot"></span><div><b>${esc(o.purpose)}</b><small>${new Date(o.at).toLocaleDateString()} · ${o.spontaneous?'Spontaneous':'Responded'} · ${esc(o.support||'Support not recorded')}</small></div></div>`).join('')||'<div class="friendly-empty"><span>💬</span><div><b>No real-life moments recorded yet.</b><p>Use Coach Me and record one everyday communication moment.</p></div></div>'}</section></div>`}
function more(){let items=[['👧','Child profiles','Strengths, communication modes and interests.','profile'],['🎯','Goals','Choose what would make everyday communication easier.','goals'],['🧭','Communication Discovery','Notice strengths and choose a useful starting point.','discovery'],['🖼️','Visual Supports','First/Then, choices, schedules, body and communication supports.','supports'],['🎓','Caregiver Academy','Short practical lessons you can use today.','academy'],['💜','Help Me Now','Simple guidance for common communication moments.','help'],['🏠','Everyday Routines','Turn ordinary routines into communication opportunities.','routines'],['👐','No Materials','Guided communication with nothing extra needed.','noMaterials'],['📖','Caregiver Handbook','A printable plain-language guide.','handbook'],['🧑‍⚕️','Professional View','A local collaboration summary for review.','professional'],['💾','Backup & Restore','Protect the WAPS information stored on this device.','backup'],['⚙️','Settings','AAC layout, sensory preferences and privacy.','settings']];return `<div class="reference-page more-page"><section class="reference-hero more-hero"><div class="hero-icon orange">▦</div><div><span class="eyebrow">MORE</span><h1>Your WAPS toolkit.</h1><p>Profiles, learning, visual supports and practical caregiver tools—all in one place.</p></div></section><section class="more-launch-grid">${items.map(x=>`<button class="more-tile" data-action="${x[3]}"><span class="more-art">${x[0]}</span><span><b>${x[1]}</b><small>${x[2]}</small></span><i>›</i></button>`).join('')}</section></div>`}
function render(){clearInterval(timerId);let r=route();if(!['home','talk','practice','coach','progress','more'].includes(r))r='home';document.body.dataset.route=r;main.innerHTML={home:home,talk:talk,practice:practice,coach:coach,progress:progress,more:more}[r]();nav();if(r==='talk'){drawAAC();drawSentence()}}
function profileModal(){let profiles=S.profiles.map(p=>`<div class="list-item"><b>${esc(p.name)}</b><div class="mini">${esc((p.modes||[]).join(', ')||'Modes not recorded')}</div><div class="actions"><button class="btn secondary choose-profile" data-id="${p.id}">Use profile</button><button class="btn ghost edit-profile" data-id="${p.id}">Edit</button></div></div>`).join('');show(`<h2>Child profiles</h2><div class="list">${profiles||'<p>No profiles yet.</p>'}</div><hr><h3>Add child</h3><div class="field"><label>Preferred name<input id="pname" maxlength="40"></label></div><div class="field"><label>Optional profile photo<input id="profilePhoto" type="file" accept="image/*"></label><div class="mini">Stored only on this device with the child profile.</div></div><div class="field"><label>Main caregiver priority<input id="priority" maxlength="120" placeholder="e.g. ask for help more easily"></label></div><div class="field"><label>Communication modes</label><div class="checks">${['Speech','AAC','Pointing','Gesture','Pictures','Signs','Writing/typing','Vocalization'].map(x=>`<label class="check"><input type="checkbox" name="mode" value="${x}">${x}</label>`).join('')}</div></div><div class="field"><label>Language context<select id="lang"><option>English</option><option>Jamaican Creole / Patwa</option><option>English + Jamaican Creole / Patwa</option><option>Other / multilingual</option></select></label></div><button class="btn" data-action="saveProfile">Save profile</button>`)}
function editProfile(id){let p=S.profiles.find(x=>x.id===id);if(!p)return;show(`<h2>Edit ${esc(p.name)}</h2><div class="profile-edit-photo">${p.photo?`<img src="${p.photo}" alt="" class="profile-photo-preview">`:''}</div><div class="field"><label>Preferred name<input id="epname" value="${esc(p.name)}"></label></div><div class="field"><label>Change profile photo<input id="editProfilePhoto" type="file" accept="image/*"></label></div><div class="field"><label>Caregiver priority<input id="epriority" value="${esc(p.priority||'')}"></label></div><div class="field"><label>Interests<input id="einterests" value="${esc((p.interests||[]).join(', '))}" placeholder="music, cars, water play"></label></div><div class="notice">WAPS does not score Jamaican Creole grammar as incorrect Standard English. Language difference and disorder are not the same thing.</div><div class="actions"><button class="btn" data-save-edit="${id}">Save</button><button class="btn danger" data-delete-profile="${id}">Delete profile</button></div>`)}
function goalsModal(){let p=active();if(!p){profileModal();return}let goals=S.goals.filter(x=>x.profile===p.id);show(`<h2>${esc(p.name)}’s goals</h2><p>Keep goals functional and observable. Aim for a small number of active priorities.</p><div class="list">${goals.map(g=>`<div class="list-item"><b>${esc(g.text)}</b><div class="mini">${g.active?'Active':'Paused'}</div><button class="btn ghost toggle-goal" data-id="${g.id}">${g.active?'Pause':'Activate'}</button></div>`).join('')||'<p>No goals yet.</p>'}</div><div class="field"><label>New functional goal<input id="goalInput" maxlength="160" placeholder="e.g. Ask for HELP using any reliable communication mode"></label></div><button class="btn" data-action="saveGoal">Add goal</button>`)}
function recommendActivity(p,g){let text=((g?.text||'')+' '+(p?.priority||'')).toLowerCase();let rules=[['help','repair-choice'],['choice','functional-choice'],['food','food-choice'],['drink','drinks'],['body','body-parts'],['feeling','feelings-more'],['school','school-tools'],['people','people-choice'],['place','places2'],['routine','routine-choice'],['word','word-picture'],['action','more-actions'],['understand','food-identify'],['aac','more-finished']];for(const [k,id] of rules)if(text.includes(k))return ACTIVITY_SETS.find(x=>x.id===id);let recent=new Set(S.sessions.filter(x=>x.profile===p?.id).slice(-5).map(x=>x.activity));return ACTIVITY_SETS.find(x=>!recent.has(x.id))||ACTIVITY_SETS[0]}
function todayModal(){let p=active();if(!p)return profileModal();let g=S.goals.find(x=>x.profile===p.id&&x.active),recent=S.sessions.filter(x=>x.profile===p.id).slice(-6),obs=S.observations.filter(x=>x.profile===p.id).slice(-6);let independent=recent.filter(x=>x.prompt==='Independent'&&x.result==='correct').length,needsSupport=recent.filter(x=>x.prompt&&x.prompt!=='Independent').length;let recommendation=needsSupport>independent?'Use an easier example and model once before waiting.':'Give a natural opportunity first and wait before helping.';let rec=recommendActivity(p,g);show(`<div class="eyebrow">WAPS guided session</div><h2>Today with ${esc(p.name)}</h2><p>You do not need speech-therapy training. Follow one step at a time and WAPS will tell you what to watch for.</p><div class="session-path"><div class="goal"><div class="num">1</div><div><b>CONNECT · 2 minutes</b><p>Join something ${esc(p.name)} already enjoys. Do not test. Copy an action, comment, smile, or simply be present.</p></div></div><div class="goal"><div class="num">2</div><div><b>MODEL · one useful message</b><p>${g?`Today's goal: ${esc(g.text)}`:'Start with a useful purpose: choice, help, break, request or comment.'} <strong>${recommendation}</strong></p></div></div><div class="goal"><div class="num">3</div><div><b>PRACTISE · 3–5 turns</b><p>Accept speech, AAC, pointing, gesture, sign, picture, typing or another clear intentional response. Communication counts even when it is not spoken.</p></div></div><div class="goal"><div class="num">4</div><div><b>USE IT · away from WAPS</b><p>Create one natural chance in a meal, play, dressing, school preparation or another routine. Then record only what happened.</p></div></div></div>${obs.length?`<div class="callout"><b>Based on recent real-life records</b><p>${obs.some(x=>x.spontaneous)?'There has been at least one spontaneous initiation. Keep creating natural opportunities without demanding a response.':'No spontaneous initiation is recorded recently. Reduce questions, model the message, then leave space for initiation.'}</p></div>`:''}<div class="actions"><button class="btn" data-close-route="coach">Guide me step by step</button><button class="btn secondary" data-start="${rec.id}">Practise: ${esc(rec.title)}</button><button class="btn ghost" data-action="observeToday">Record real-life use</button></div>`) }
function supportsModal(){show(`<h2>Visual supports</h2><p>Build supports for real routines. These are communication aids—not behaviour-compliance charts.</p><div class="tool-grid"><div class="support-board"><h3>First → Then</h3><div class="field"><input id="firstText" placeholder="First"></div><div class="field"><input id="thenText" placeholder="Then"></div><button class="btn secondary" data-action="makeFirstThen">Create</button><div id="firstThenOut"></div></div><div class="support-board"><h3>Choice board</h3><div class="field"><input id="choiceA" placeholder="Choice 1"></div><div class="field"><input id="choiceB" placeholder="Choice 2"></div><button class="btn secondary" data-action="makeChoice">Create</button><div id="choiceOut"></div></div><div class="support-board"><h3>Now → Next → Later</h3><input id="sched1" placeholder="Now"><input id="sched2" placeholder="Next"><input id="sched3" placeholder="Later"><button class="btn secondary" data-action="makeSchedule">Create schedule</button><div id="scheduleOut"></div></div><div class="support-board"><h3>Visual timer</h3><div class="session-choice"><button class="btn secondary timer-start" data-seconds="60">1 min</button><button class="btn secondary timer-start" data-seconds="180">3 min</button><button class="btn secondary timer-start" data-seconds="300">5 min</button><button class="btn secondary timer-start" data-seconds="600">10 min</button></div><div id="visualTimer" class="big-timer">—</div></div></div><div class="support-board" style="margin-top:14px"><h3>Feelings, body & needs</h3><div class="actions"><button class="btn secondary" data-support-board="feelings">Feelings</button><button class="btn secondary" data-support-board="body">Body / hurts</button><button class="btn secondary" data-support-board="safety">Help / break / stop</button></div><div id="supportVisuals" class="tool-grid" style="margin-top:12px"></div></div><div class="support-board" style="margin-top:14px"><h3>Communication passport</h3><p>Print a simple summary of how the child communicates and what partners should know.</p><button class="btn secondary" data-action="passport">Create passport</button></div>`) }
function academyModal(){let done=S.settings.academyDone||[],pct=Math.round(done.length/LESSONS.length*100);show(`<h2>Caregiver Academy</h2><p>Learn one idea, use it immediately, then mark it practised. No clinical vocabulary required.</p><div class="academy-progress"><span style="width:${pct}%"></span></div><p class="mini">${done.length} of ${LESSONS.length} practised</p>${LESSONS.map((x,i)=>`<details class="lesson"><summary><b>${done.includes(i)?'✓ ':''}${i+1}. ${esc(x[0])}</b></summary><p>${esc(x[1])}</p><div class="notice"><b>Try it:</b> ${esc(x[2])}</div><button class="btn secondary academy-done" data-lesson="${i}" style="margin-top:10px">${done.includes(i)?'Practised ✓':'I practised this'}</button></details>`).join('')}`)}
function discoveryModal(){let p=active();if(!p)return profileModal();show(`<h2>Communication discovery</h2><p>This is not a test or diagnosis. Notice what ${esc(p.name)} already does and choose what would make daily life easier.</p><div class="discovery-step"><b>1 · How does communication happen now?</b><p>${esc((p.modes||[]).join(', ')||'Add communication modes in the profile.')}</p></div><div class="discovery-step"><b>2 · Watch for purpose</b><p>During one familiar routine, notice requesting, rejecting, commenting, asking for help, choosing, greeting or sharing attention.</p></div><div class="discovery-step"><b>3 · Notice independence</b><p>Did the message happen independently, after a natural cue, or after direct help?</p></div><div class="discovery-step"><b>4 · Choose one priority</b><p>Current caregiver priority: <strong>${esc(p.priority||'not recorded yet')}</strong></p></div><div class="actions"><button class="btn" data-action="goals">Turn priority into a goal</button><button class="btn secondary" data-observe="Communication discovery">Record what I noticed</button></div>`)}
function enterChildMode(){document.body.insertAdjacentHTML('beforeend',`<div class="child-lock" id="childLock"><div class="child-top"><div class="brand"><img src="./assets/icons/icon.svg" alt=""><span><b>WAPS</b><small>Child Mode</small></span></div><button class="btn ghost hold-exit" id="holdExit">Hold to exit</button></div><div class="child-content"><div class="hero"><h1>What do you want to do?</h1><p>Talk, practise, or ask for help.</p><div class="actions"><button class="btn light child-go" data-child-route="talk">Talk</button><button class="btn secondary child-go" data-child-route="practice">Practise</button><button class="btn secondary child-go" data-child-route="coach">Help together</button></div></div><div class="notice"><b>Your communication matters.</b> You can say NO, STOP, HELP or BREAK at any time.</div></div></div>`)}
function routinesModal(){show(`<h2>Everyday communication routines</h2><p>Choose a routine already happening today. Keep communication useful and natural.</p><div class="list">${ROUTINES.map(x=>`<details class="lesson"><summary><b>${esc(x[0])}</b></summary><p>${esc(x[1])}</p><button class="btn secondary" data-observe="${esc(x[0])}">Record real-life use</button></details>`).join('')}</div>`)}
function noMaterialsModal(){show(`<h2>No materials needed</h2><p>Use the people and environment already around you.</p>${NO_MATERIALS.map((x,i)=>`<div class="notice" style="margin:10px 0"><h3>${i+1}. ${esc(x[0])}</h3><p>${esc(x[1])}</p></div>`).join('')}<button class="btn" data-close-route="coach">Guide me through a routine</button>`)}
function handbookModal(){show(`<div id="handbook"><div class="eyebrow">WAPS caregiver handbook</div><h1>Helping communication grow in everyday life</h1><p>Plain-language principles for home communication support.</p>${HANDBOOK.map((x,i)=>`<section class="handbook-section"><h2>${i+1}. ${esc(x[0])}</h2><p>${esc(x[1])}</p></section>`).join('')}<div class="notice"><b>Clinical boundary:</b> WAPS supports home communication practice. It is not a standardized assessment, diagnosis, or substitute for individualized professional care when that is needed.</div></div><button class="btn" data-action="print">Print / Save PDF</button>`)}
function helpModal(){show(`<h2>Help me now</h2><p>Select what sounds closest. WAPS gives practical guidance, not a diagnosis.</p><div class="list">${HELP.map((x,i)=>`<button class="list-item help-item" data-help="${i}" style="text-align:left"><b>${esc(x[0])}</b></button>`).join('')}</div><div id="helpAnswer"></div>`)}
function settingsModal(){show(`<h2>Settings & privacy</h2><div class="field"><label>AAC grid columns<select id="gridSetting"><option ${S.settings.grid==3?'selected':''}>3</option><option ${S.settings.grid==4?'selected':''}>4</option><option ${S.settings.grid==5?'selected':''}>5</option></select></label></div><label class="check"><input id="reduceSetting" type="checkbox" ${S.settings.reduced?'checked':''}> Reduce motion</label><label class="check"><input id="stimSetting" type="checkbox" ${S.settings.lowStim?'checked':''}> Lower visual stimulation</label><div class="notice" style="margin-top:14px"><b>Privacy:</b> no ads, trackers or account are included. Core profile/progress data are stored locally in this browser. Browser/device storage can still be cleared or lost, so export backups.</div><div class="actions"><button class="btn" data-action="saveSettings">Save settings</button><button class="btn danger" data-action="resetAll">Reset all local WAPS data</button></div>`)}
function professionalModal(){let p=active(),g=S.goals.filter(x=>x.profile===S.active),ss=S.sessions.filter(x=>x.profile===S.active),obs=S.observations.filter(x=>x.profile===S.active);show(`<h2>Professional view</h2><div class="notice warn">Local collaboration view only. This is not secure remote clinical software and does not create a diagnosis.</div>${p?`<h3>${esc(p.name)}</h3><p><b>Caregiver priority:</b> ${esc(p.priority||'Not recorded')}</p><p><b>Communication modes:</b> ${esc((p.modes||[]).join(', ')||'Not recorded')}</p><p><b>Language context:</b> ${esc(p.language||'Not recorded')}</p><h3>Goals</h3>${g.map(x=>`<p>• ${esc(x.text)} ${x.active?'(active)':'(paused)'}</p>`).join('')||'<p>None recorded.</p>'}<h3>Recorded data</h3><p>${ss.length} sessions · ${obs.length} observations</p><button class="btn secondary" data-action="report">Print / save summary</button>`:'<p>Create a child profile first.</p>'}`)}
function customAACModal(){show(`<h2>Add personal communication</h2><div class="field"><label>Word or short phrase<input id="customLabel" maxlength="60"></label></div><div class="field"><label>Optional photo<input id="customPhoto" type="file" accept="image/*"></label></div><p class="mini">Photos are resized in your browser and stored locally with WAPS data. They are not uploaded by this static app.</p><button class="btn" data-action="saveCustomAAC">Add to WAPS Talk</button>`)}
function recordObservation(purpose='Communication'){show(`<h2>Real-life observation</h2><p>Record only what you observed.</p><div class="field"><label>Communication purpose<input id="obsPurpose" value="${esc(purpose)}"></label></div><div class="field"><label>Support<select id="obsSupport"><option>Independent</option><option>Natural cue</option><option>Visual support</option><option>Gesture</option><option>Verbal cue</option><option>Model</option><option>Direct assistance</option></select></label></div><label class="check"><input id="obsSpont" type="checkbox"> Initiated spontaneously</label><button class="btn" data-action="saveObservation">Save observation</button>`)}
function report(){let p=active(),ss=S.sessions.filter(x=>x.profile===S.active),obs=S.observations.filter(x=>x.profile===S.active),goals=S.goals.filter(x=>x.profile===S.active);show(`<div id="printReport"><div class="eyebrow">WAPS Communication</div><h1>${esc(p?.name||'Child')} — communication summary</h1><p class="mini">Generated ${new Date().toLocaleString()}</p><p><b>Caregiver priority:</b> ${esc(p?.priority||'Not recorded')}</p><p><b>Communication modes:</b> ${esc((p?.modes||[]).join(', ')||'Not recorded')}</p><h3>Goals</h3>${goals.map(x=>`<p>• ${esc(x.text)} — ${x.active?'active':'paused'}</p>`).join('')||'<p>None recorded.</p>'}<h3>Recorded activity</h3><p>${ss.length} WAPS sessions; ${obs.length} real-life/caregiver observations.</p><h3>Recent observations</h3>${obs.slice(-10).map(x=>`<p>• ${new Date(x.at).toLocaleDateString()}: ${esc(x.purpose)} — ${esc(x.support)}${x.spontaneous?' — spontaneous':''}</p>`).join('')||'<p>None recorded.</p>'}<div class="notice">This report summarizes WAPS activity and caregiver-recorded observations. It is not a standardized assessment or diagnosis.</div></div><button class="btn" data-action="print">Print / Save PDF</button>`)}
function download(name,text,type='application/json'){let u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function photoData(file){if(!file)return null;return await new Promise((res,rej)=>{let img=new Image(),r=new FileReader();r.onload=()=>{img.onload=()=>{let max=360,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',.78))};img.onerror=rej;img.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
document.addEventListener('click',async e=>{
  const el=e.target instanceof Element?e.target:null;if(!el)return;
  let routeBtn=el.closest('[data-route]');if(routeBtn){e.preventDefault();go(routeBtn.dataset.route);return}
  let st=el.closest('[data-start]');if(st){e.preventDefault();if(modal.open)modal.close();activity(st.dataset.start);return}
  let ch=el.closest('[data-choice]');if(ch){e.preventDefault();let correct=ch.dataset.choice===ch.dataset.target,a=currentAct,prompt=$('#promptLevel')?.value||'Not recorded';S.sessions.push({id:crypto.randomUUID(),profile:S.active,at:now(),type:'practice',activity:a.id,domain:a.domain,result:correct?'correct':'supported/retry',prompt,source:'WAPS activity'});await persist();let fb=$('#feedback');if(fb)fb.innerHTML=\`<div class="feedback \${correct?'good':'support'}"><b>\${correct?'That matches.':'Support the learning.'}</b><p>\${correct?'Notice how much help was needed, then use the idea in real life.':'Model the target, reduce the choices if needed, and keep the interaction positive.'}</p><button class="btn secondary" data-observe="\${esc(a.domain)}">Record real-life use</button> <button class="btn ghost" data-start="\${a.id}">Try another</button></div>\`;return}
  let cr=el.closest('[data-coach]');if(cr){e.preventDefault();coachScreen(cr.dataset.coach);return}
  let ob=el.closest('[data-observe]');if(ob){e.preventDefault();recordObservation(ob.dataset.observe);return}
  let support=el.closest('.support-choice');if(support){e.preventDefault();$$('.support-choice').forEach(x=>x.classList.toggle('active',x===support));let sel=$('#promptLevel');if(sel)sel.value=support.dataset.support;return}
  let p=el.closest('.choose-profile');if(p){e.preventDefault();S.active=p.dataset.id;await persist();modal.close();render();return}
  let ep=el.closest('.edit-profile');if(ep){e.preventDefault();editProfile(ep.dataset.id);return}
  let sv=el.closest('[data-save-edit]');if(sv){e.preventDefault();let p=S.profiles.find(x=>x.id===sv.dataset.saveEdit);if(!p)return;p.name=$('#epname').value.trim()||p.name;p.priority=$('#epriority').value.trim();p.interests=$('#einterests').value.split(',').map(x=>x.trim()).filter(Boolean);try{let file=$('#editProfilePhoto')?.files?.[0];if(file)p.photo=await photoData(file)}catch{}await persist();modal.close();render();toast('Profile updated');return}
  let del=el.closest('[data-delete-profile]');if(del){e.preventDefault();if(confirm('Delete this child profile and its WAPS records? This cannot be undone unless you have a backup.')){let id=del.dataset.deleteProfile;S.profiles=S.profiles.filter(x=>x.id!==id);S.sessions=S.sessions.filter(x=>x.profile!==id);S.observations=S.observations.filter(x=>x.profile!==id);S.goals=S.goals.filter(x=>x.profile!==id);S.customAAC=S.customAAC.filter(x=>x.profile!==id);S.active=S.profiles[0]?.id||null;await persist();modal.close();render()}return}
  let tg=el.closest('.toggle-goal');if(tg){e.preventDefault();let g=S.goals.find(x=>x.id===tg.dataset.id);if(g){g.active=!g.active;await persist();goalsModal()}return}
  let h=el.closest('.help-item');if(h){e.preventDefault();let x=HELP[Number(h.dataset.help)],out=$('#helpAnswer');if(out&&x)out.innerHTML=\`<div class="notice" style="margin-top:14px"><h3>\${esc(x[0])}</h3><p>\${esc(x[1])}</p></div>\`;return}
  let co=el.closest('.coach-outcome');if(co){e.preventDefault();S.sessions.push({id:crypto.randomUUID(),profile:S.active,at:now(),type:'coach',activity:coachRun.id,domain:'Caregiver coaching',result:co.dataset.result,prompt:co.dataset.result==='Independent'?'Independent':co.dataset.result,source:'Caregiver guided interaction'});await persist();modal.close();recordObservation(coachRun.title);return}
  let aac=el.closest('.aac');if(aac){e.preventDefault();sentence.push(aac.dataset.word);drawSentence();return}
  let cat=el.closest('.aac-cat');if(cat){e.preventDefault();aacCat=cat.dataset.cat;$$('.aac-cat').forEach(x=>x.setAttribute('aria-pressed',x===cat?'true':'false'));drawAAC();return}
  let closer=el.closest('[data-close-route]');if(closer){e.preventDefault();if(modal.open)modal.close();go(closer.dataset.closeRoute);return}
  let ad=el.closest('.academy-done');if(ad){e.preventDefault();let i=Number(ad.dataset.lesson);S.settings.academyDone=S.settings.academyDone||[];if(!S.settings.academyDone.includes(i))S.settings.academyDone.push(i);await persist();academyModal();return}
  let sb=el.closest('[data-support-board]');if(sb){e.preventDefault();let ids=sb.dataset.supportBoard==='feelings'?['happy','sad','tired','angry']:sb.dataset.supportBoard==='body'?['head','hand','foot','ear','mouth','hurts']:['help','break','stop','no'];let out=$('#supportVisuals');if(out)out.innerHTML=ids.map(id=>\`<div class="visual-tile"><div>\${visualHTML(id,'support-photo')}<div>\${esc(concept[id].label)}</div></div></div>\`).join('');return}
  let ts=el.closest('.timer-start');if(ts){e.preventDefault();clearInterval(timerId);let n=Number(ts.dataset.seconds),out=$('#visualTimer');let draw=()=>{let m=Math.floor(n/60),sec=n%60;if(out)out.textContent=\`\${m}:\${String(sec).padStart(2,'0')}\`};draw();timerId=setInterval(()=>{n--;draw();if(n<=0){clearInterval(timerId);if(out)out.textContent='Finished'}},1000);return}
  let cg=el.closest('.child-go');if(cg){e.preventDefault();document.querySelector('#childLock')?.remove();go(cg.dataset.childRoute);return}
  let a=el.closest('[data-action]')?.dataset.action;if(!a)return;e.preventDefault();
  if(a==='closeModal'){if(modal.open)modal.close();return}
  if(a==='childMode'){if(modal.open)modal.close();enterChildMode();return}
  if(a==='discovery'){discoveryModal();return}
  if(a==='observeToday'){if(modal.open)modal.close();recordObservation('Today’s communication goal');return}
  if(a==='profile'){profileModal();return}
  if(a==='goals'){goalsModal();return}
  if(a==='today'){todayModal();return}
  if(a==='supports'){supportsModal();return}
  if(a==='academy'){academyModal();return}
  if(a==='help'){helpModal();return}
  if(a==='settings'){settingsModal();return}
  if(a==='professional'){professionalModal();return}
  if(a==='routines'){routinesModal();return}
  if(a==='noMaterials'){noMaterialsModal();return}
  if(a==='handbook'){handbookModal();return}
  if(a==='about'){show('<h2>About WAPS</h2><p>WAPS supports caregiver-guided communication practice, AAC access and real-world generalization. It does not diagnose autism, language disorder, speech-sound disorder or motor-speech conditions, and it does not replace qualified professional care.</p>');return}
  if(a==='customAAC'){customAACModal();return}
  if(a==='speak'){let text=sentence.join(' ');if(text&&'speechSynthesis'in window&&typeof SpeechSynthesisUtterance!=='undefined'){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text.toLowerCase()))}else if(text)toast('Speech is not available on this device. The message remains visible.');return}
  if(a==='backspace'){if(sentence.length)sentence.pop();drawSentence();return}
  if(a==='clearSentence'){sentence.splice(0,sentence.length);drawSentence();return}
  if(a==='partner'){partner=!partner;let ps=$('#partnerState'),pt=$('#partnerTip');if(ps)ps.textContent=partner?'On':'Off';if(pt)pt.classList.toggle('hidden',!partner);return}
  if(a==='repeatPrompt'){let t=$('.prompt')?.textContent?.trim();if(t&&'speechSynthesis'in window&&typeof SpeechSynthesisUtterance!=='undefined'){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}else if(t)toast('Read-aloud is not available on this device.');return}
  if(a==='speakPage'){let t=main?.innerText?.replace(/\s+/g,' ').trim();if(t&&'speechSynthesis'in window&&typeof SpeechSynthesisUtterance!=='undefined'){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t.slice(0,3500)))}else toast('Read-aloud is not available on this device.');return}
  if(a==='coachPrev'){if(coachStep>0){coachStep--;drawCoachStep()}return}
  if(a==='coachNext'){if(coachStep<coachRun.steps.length-1){coachStep++;drawCoachStep()}else{show('<h2>Record the interaction</h2><p>What happened?</p><div class="outcomes"><button class="btn secondary coach-outcome" data-result="Independent">Independent</button><button class="btn secondary coach-outcome" data-result="With help">With help</button><button class="btn secondary coach-outcome" data-result="Not yet">Not yet</button><button class="btn secondary coach-outcome" data-result="No opportunity">No opportunity</button></div>')}return}
  if(a==='saveProfile'){let name=$('#pname')?.value.trim();if(!name){toast('Add a preferred name.');return}let modes=$$('input[name=mode]:checked').map(x=>x.value),id=crypto.randomUUID(),photo=null;try{photo=await photoData($('#profilePhoto')?.files?.[0])}catch{}let priority=$('#priority')?.value.trim()||'';S.profiles.push({id,name,photo,priority,modes,language:$('#lang')?.value||'English',interests:[],created:now()});S.active=id;if(priority)S.goals.push({id:crypto.randomUUID(),profile:id,text:\`Communicate about: \${priority}\`,active:true,created:now()});await persist();modal.close();render();toast('Profile saved');return}
  if(a==='saveGoal'){let t=$('#goalInput')?.value.trim();if(t){S.goals.push({id:crypto.randomUUID(),profile:S.active,text:t,active:S.goals.filter(x=>x.profile===S.active&&x.active).length<3,created:now()});await persist();goalsModal()}return}
  if(a==='makeFirstThen'){let f=$('#firstText')?.value.trim(),t=$('#thenText')?.value.trim(),out=$('#firstThenOut');if(out)out.innerHTML=\`<div class="support-grid" style="margin-top:12px"><div class="support-panel"><div><div class="eyebrow">FIRST</div><strong>\${esc(f||'First activity')}</strong></div></div><div class="support-panel"><div><div class="eyebrow">THEN</div><strong>\${esc(t||'Then activity')}</strong></div></div></div>\`;return}
  if(a==='makeSchedule'){let vals=[$('#sched1')?.value,$('#sched2')?.value,$('#sched3')?.value].map(x=>(x||'').trim()).filter(Boolean),out=$('#scheduleOut');if(out)out.innerHTML='<div class="schedule-list" style="margin-top:12px">'+vals.map((v,i)=>\`<div class="schedule-row"><b>\${i+1}</b><span>\${esc(v)}</span><span>○</span></div>\`).join('')+'</div>';return}
  if(a==='makeChoice'){let x=$('#choiceA')?.value.trim(),y=$('#choiceB')?.value.trim(),out=$('#choiceOut');if(out)out.innerHTML=\`<div class="support-grid" style="margin-top:12px"><div class="support-panel"><strong>\${esc(x||'Choice 1')}</strong></div><div class="support-panel"><strong>\${esc(y||'Choice 2')}</strong></div></div>\`;return}
  if(a==='passport'){let p=active();show(\`<div id="passport"><div class="eyebrow">Communication passport</div><h1>\${esc(p?.name||'My communication')}</h1><p><b>I communicate using:</b> \${esc((p?.modes||[]).join(', ')||'Please ask my caregiver')}</p><p><b>What matters right now:</b> \${esc(p?.priority||'Please ask me and give me time to respond.')}</p><p><b>Helpful partner reminder:</b> Notice all communication modes. Give me time. Model—don’t demand. Respect NO, STOP and BREAK.</p></div><button class="btn" data-action="print">Print</button>\`);return}
  if(a==='backup'){download(\`WAPS-backup-\${new Date().toISOString().slice(0,10)}.json\`,JSON.stringify({format:'WAPS-BACKUP',schema:2,appVersion:'1.0.0',exported:now(),data:S},null,2));return}
  if(a==='saveSettings'){S.settings.grid=Number($('#gridSetting')?.value||4);S.settings.reduced=!!$('#reduceSetting')?.checked;S.settings.lowStim=!!$('#stimSetting')?.checked;await persist();document.documentElement.dataset.lowStim=S.settings.lowStim?'1':'0';modal.close();render();toast('Settings saved');return}
  if(a==='resetAll'){if(confirm('Delete all WAPS data stored in this browser? Export a backup first if you need it.')){await clearAll();S=fresh();modal.close();render();toast('Local WAPS data reset')}return}
  if(a==='report'){report();return}
  if(a==='print'){window.print();return}
  if(a==='saveCustomAAC'){let label=$('#customLabel')?.value.trim().toUpperCase();if(!label){toast('Add a word or phrase.');return}let file=$('#customPhoto')?.files?.[0],photo=null;try{photo=await photoData(file)}catch{}S.customAAC.push({id:crypto.randomUUID(),profile:S.active,label,photo,created:now()});await persist();modal.close();if(route()==='talk')drawAAC();toast('Personal word added');return}
  if(a==='saveObservation'){S.observations.push({id:crypto.randomUUID(),profile:S.active,at:now(),context:'real-life',purpose:$('#obsPurpose')?.value.trim()||'Communication',support:$('#obsSupport')?.value||'Not recorded',spontaneous:!!$('#obsSpont')?.checked,source:'Caregiver real-world observation'});await persist();modal.close();toast('Observation saved');if(route()==='progress')render();return}
});
document.addEventListener('change',async e=>{if(e.target.id==='restoreFile'){let file=e.target.files[0];if(!file)return;try{let j=JSON.parse(await file.text());if(j.format!=='WAPS-BACKUP'||j.schema!==2||!j.data||!Array.isArray(j.data.profiles))throw Error('format');if(confirm(`Restore backup from ${new Date(j.exported).toLocaleString()}? This will replace current local WAPS data.`)){S=j.data;await persist();modal.close();render();toast('Backup restored')}}catch(err){alert('This is not a valid compatible WAPS backup. Current data were not changed.')}e.target.value=''}});

let holdTimer;document.addEventListener('pointerdown',e=>{if(e.target.closest('#holdExit'))holdTimer=setTimeout(()=>document.querySelector('#childLock')?.remove(),1600)});document.addEventListener('pointerup',()=>clearTimeout(holdTimer));
window.addEventListener('hashchange',render);window.addEventListener('online',()=>$('#offlineBanner').classList.add('hidden'));window.addEventListener('offline',()=>$('#offlineBanner').classList.remove('hidden'));if(!navigator.onLine)$('#offlineBanner').classList.remove('hidden');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);render();
