
import {IDENTIFY_COLOURS,IDENTIFY_SHAPES,COLOUR_PRESETS,SHAPE_PRESETS,COLOUR_BASE_SHAPES,SHAPE_COMMON_COLOURS,validateIdentifyData} from './identify-data.js';

export function createIdentifyFeature(ctx){
  const {getState,persist,active,show,toast,main,modal,go,esc,celebrate}=ctx;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const clone=v=>JSON.parse(JSON.stringify(v));
  const colours=Object.fromEntries(IDENTIFY_COLOURS.map(x=>[x.id,x]));
  const shapes=Object.fromEntries(IDENTIFY_SHAPES.map(x=>[x.id,x]));
  const defaults={
    colours:{type:'colours',selected:[...COLOUR_PRESETS.early],choices:3,showWord:true,autoSpeak:true,celebration:true,sessionLength:'continuous'},
    shapes:{type:'shapes',selected:[...SHAPE_PRESETS.early],choices:3,showWord:true,autoSpeak:true,celebration:true,sessionLength:'continuous'}
  };
  const praise=['Great job!','You found it!','Yes!','Nice looking!','Well done!'];
  let draft=null,current=null,nextTimer=null,speakTimer=null;
  function state(){const S=getState();if(!S.identify||typeof S.identify!=='object')S.identify={prefs:{},sessions:{},history:[]};S.identify.prefs=S.identify.prefs||{};S.identify.sessions=S.identify.sessions||{};S.identify.history=Array.isArray(S.identify.history)?S.identify.history:[];return S.identify}
  const profileKey=()=>getState().active||'global';
  function bucket(obj,key){if(!obj[key])obj[key]={};return obj[key]}
  function prefs(type){const b=bucket(state().prefs,profileKey());if(!b[type])b[type]=clone(defaults[type]);return b[type]}
  function session(type){return bucket(state().sessions,profileKey())[type]||null}
  function saveSession(type,v){bucket(state().sessions,profileKey())[type]=v}
  function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function makeDeck(selected,last){const d=shuffle(selected);if(d.length>1&&d[0]===last){const j=1+Math.floor(Math.random()*(d.length-1));[d[0],d[j]]=[d[j],d[0]]}return d}
  function makePosQueue(n,last){const q=shuffle(Array.from({length:n},(_,i)=>i));if(q.length>1&&q[0]===last){[q[0],q[1]]=[q[1],q[0]]}return q}
  function signature(p){return JSON.stringify([p.selected,p.choices,p.showWord,p.autoSpeak,p.celebration,p.sessionLength])}
  function cleanup(){clearTimeout(nextTimer);clearTimeout(speakTimer);nextTimer=speakTimer=null;if('speechSynthesis'in window)speechSynthesis.cancel();document.body.classList.remove('identify-active');current=null}
  function label(type,id){return type==='colours'?colours[id]?.label:shapes[id]?.label}
  function selectionData(type){return type==='colours'?IDENTIFY_COLOURS:IDENTIFY_SHAPES}
  function presetData(type){return type==='colours'?COLOUR_PRESETS:SHAPE_PRESETS}
  function shapeSvg(id,fill,stroke){const s=shapes[id];if(!s)return '';return "<svg class='identify-shape-svg' viewBox='0 0 100 100' aria-hidden='true' style='--shape-fill:"+fill+";--shape-stroke:"+(stroke||fill)+"'><g>"+s.svg+"</g></svg>"}
  function launch(){cleanup();show("<div class='identify-launch'><span class='eyebrow'>WAPS COLOURS & SHAPES</span><h1>What would you like to identify?</h1><p>Simple visual choices. The target changes after every correct response.</p><div class='identify-type-grid'><button data-identify-type='colours'><span>🎨</span><b>Colours</b><small>Same shape, different colours</small></button><button data-identify-type='shapes'><span>🔷</span><b>Shapes</b><small>Same colour, different shapes</small></button></div><div class='notice'><b>Learning safeguard:</b> colour questions change only colour. Shape questions change only shape, so the child cannot rely on an unrelated visual clue.</div></div>",true)}
  function config(type){const p=prefs(type);draft={...clone(p),selected:[...(p.selected||defaults[type].selected)],type};renderConfig()}
  function renderConfig(){
    const type=draft.type,isColour=type==='colours',items=selectionData(type),presets=presetData(type),order=isColour?['starter','early','core','full']:['starter','early','core','expanded','advanced'];
    const presetHtml=order.map(k=>"<button data-identify-preset='"+k+"'>"+k[0].toUpperCase()+k.slice(1)+"</button>").join('');
    const tokenHtml=items.map(x=>{const visual=isColour?"<i class='identify-colour-dot' style='--stimulus:"+x.value+";--stimulus-outline:"+(x.outline||x.value)+"'></i>":shapeSvg(x.id,'#1E88E5','#155D8C');return "<button class='"+(draft.selected.includes(x.id)?'selected':'')+"' data-identify-token='"+x.id+"'>"+visual+"<b>"+esc(x.label)+"</b></button>"}).join('');
    const restart=session(type)?"<button class='btn ghost' data-action='identifyRestartSet'>Restart saved set</button>":'',colourNote=isColour?"<div class='notice'><b>Colour accessibility:</b> colour activities rely on colour discrimination. If a child has a known colour-vision difference, choose clearly separated colours or use Shapes. WAPS does not diagnose colour vision.</div>":'';
    show("<div class='identify-config'><button class='btn ghost' data-action='identifyLaunch'>← Colours & Shapes</button><span class='eyebrow'>"+(isColour?'COLOURS':'SHAPES')+"</span><h1>Choose what to practise.</h1><div class='identify-presets'>"+presetHtml+"</div><div class='identify-token-grid'>"+tokenHtml+"</div><div class='identify-setting-grid'><label>Choices<select id='identifyChoices'><option value='2' "+(draft.choices==2?'selected':'')+">2</option><option value='3' "+(draft.choices==3?'selected':'')+">3</option><option value='4' "+(draft.choices==4?'selected':'')+">4</option></select></label><label>Session<select id='identifyLength'><option value='5' "+(draft.sessionLength==='5'?'selected':'')+">5 questions</option><option value='10' "+(draft.sessionLength==='10'?'selected':'')+">10 questions</option><option value='15' "+(draft.sessionLength==='15'?'selected':'')+">15 questions</option><option value='continuous' "+(draft.sessionLength==='continuous'?'selected':'')+">Continuous</option></select></label><label class='identify-check'><input id='identifyShowWord' type='checkbox' "+(draft.showWord?'checked':'')+"> Show word</label><label class='identify-check'><input id='identifyAutoSpeak' type='checkbox' "+(draft.autoSpeak?'checked':'')+"> Auto-speak</label><label class='identify-check'><input id='identifyCelebration' type='checkbox' "+(draft.celebration?'checked':'')+"> Celebration</label></div><div class='identify-config-summary'><b id='identifySelectedCount'>"+draft.selected.length+" selected</b><span>Minimum 2. Settings are remembered per child.</span></div>"+colourNote+"<div class='actions'><button class='btn' data-action='identifyStart'>Start →</button>"+restart+"</div></div>",true)
  }
  function preset(code){draft.selected=[...(presetData(draft.type)[code]||draft.selected)];renderConfig()}
  function toggleToken(id,button){const has=draft.selected.includes(id);draft.selected=has?draft.selected.filter(x=>x!==id):[...draft.selected,id];button?.classList.toggle('selected',!has);const o=$('#identifySelectedCount');if(o)o.textContent=draft.selected.length+' selected'}
  function readConfig(){draft.choices=Number($('#identifyChoices')?.value||3);draft.sessionLength=$('#identifyLength')?.value||'continuous';draft.showWord=!!$('#identifyShowWord')?.checked;draft.autoSpeak=!!$('#identifyAutoSpeak')?.checked;draft.celebration=!!$('#identifyCelebration')?.checked;draft.selected=[...new Set(draft.selected)]}
  async function start(){readConfig();if(draft.selected.length<2){toast('Choose at least two '+(draft.type==='colours'?'colours':'shapes')+'.');return}draft.choices=Math.max(2,Math.min(draft.choices,draft.selected.length));bucket(state().prefs,profileKey())[draft.type]=clone(draft);let s=session(draft.type),sig=signature(draft);if(!s||s.signature!==sig||!Array.isArray(s.deck)||!s.deck.length){s={type:draft.type,signature:sig,deck:makeDeck(draft.selected,null),cursor:0,round:1,lastTarget:null,lastPos:null,posQueue:[],visualIndex:0,sessionCount:0,started:new Date().toISOString()};saveSession(draft.type,s)}await persist();if(modal.open)modal.close();renderQuestion(draft.type)}
  function refillRound(s,p){const previous=s.lastTarget;s.deck=makeDeck(p.selected,previous);s.cursor=0;s.round=(s.round||1)+1;s.posQueue=[];s.visualIndex=(s.visualIndex||0)+1}
  function nextPosition(s,n){if(!Array.isArray(s.posQueue)||!s.posQueue.length||s.posQueue.some(x=>x>=n))s.posQueue=makePosQueue(n,s.lastPos);const pos=s.posQueue.shift();s.lastPos=pos;return pos}
  function buildQuestion(type){const p=prefs(type),s=session(type);if(!s||!s.deck?.length)return null;const target=s.deck[s.cursor],n=Math.min(p.choices,p.selected.length),distractors=shuffle(p.selected.filter(x=>x!==target)).slice(0,n-1),pos=nextPosition(s,n),ids=[...distractors];ids.splice(pos,0,target);const vi=(s.visualIndex+s.cursor+s.round)%1000;if(type==='colours')return {type,target,ids,baseShape:COLOUR_BASE_SHAPES[vi%COLOUR_BASE_SHAPES.length],round:s.round};const common=colours[SHAPE_COMMON_COLOURS[vi%SHAPE_COMMON_COLOURS.length]]||IDENTIFY_COLOURS[1];return {type,target,ids,commonColour:common,round:s.round}}
  function renderStimulus(q,id){if(q.type==='colours'){const col=colours[id];return shapeSvg(q.baseShape,col.value,col.outline||col.value)}return shapeSvg(id,q.commonColour.value,q.commonColour.outline||q.commonColour.value)}
  function sessionCounter(type){const p=prefs(type),s=session(type),limit=p.sessionLength==='continuous'?null:Number(p.sessionLength);return limit?(s.sessionCount+1)+' / '+limit:'Round '+s.round}
  function renderQuestion(type){clearTimeout(nextTimer);nextTimer=null;document.body.classList.add('identify-active');const p=prefs(type),s=session(type);if(!s){go('practice');return}if(s.cursor>=s.deck.length){roundComplete(type);return}const q=buildQuestion(type);if(!q)return;current={q,attempts:0,cueUsed:false,lastTapAt:0,locked:false,started:performance.now()};const targetLabel=label(type,q.target),instruction=type==='colours'?'Find '+targetLabel.toUpperCase()+'.':'Find the '+targetLabel.toUpperCase()+'.';const choices=q.ids.map(id=>"<button class='identify-choice' data-identify-choice='"+id+"'>"+renderStimulus(q,id)+(p.showWord?"<b>"+esc(label(type,id))+"</b>":'')+"</button>").join('');main.innerHTML="<div class='identify-child-screen "+type+"'><header class='identify-child-head'><button data-action='identifyExit' class='identify-back'>←</button><div><span>"+(type==='colours'?'COLOURS':'SHAPES')+"</span><b>"+esc(instruction)+"</b></div><div class='identify-count'>"+esc(sessionCounter(type))+"</div></header><div class='identify-answer-grid choices-"+q.ids.length+"'>"+choices+"</div><div class='identify-footer'><button data-action='identifyHear'>🔊 Hear again</button><div id='identifyFeedback' aria-live='polite'>Choose one.</div></div></div>";if(p.autoSpeak)speakTimer=setTimeout(speakInstruction,230)}
  function speak(text){if(!('speechSynthesis'in window)||typeof SpeechSynthesisUtterance==='undefined')return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.83;u.pitch=1.02;speechSynthesis.speak(u)}
  function speakInstruction(){if(!current)return;const t=label(current.q.type,current.q.target);speak(current.q.type==='colours'?'Find '+t:'Find the '+t)}
  function praiseFor(target,type){const base=praise[Math.floor(Math.random()*praise.length)],name=label(type,target).toUpperCase();return Math.random()<.62?'Yes — '+name+'!':base}
  async function choose(id,button){if(!current||current.locked)return;const q=current.q,now=performance.now();current.attempts++;const rapid=current.lastTapAt&&now-current.lastTapAt<300;current.lastTapAt=now;if(id!==q.target){button.classList.add('try-again');setTimeout(()=>button.classList.remove('try-again'),420);const fb=$('#identifyFeedback');if(fb)fb.textContent=rapid?'Take your time. Look carefully.':'Try again.';if(current.attempts>=3){current.cueUsed=true;const right=$("[data-identify-choice='"+q.target+"']");right?.classList.add('support-cue');setTimeout(()=>right?.classList.remove('support-cue'),900)}return}current.locked=true;$$('[data-identify-choice]').forEach(x=>x.disabled=true);button.classList.add('correct');const p=prefs(q.type),s=session(q.type),responseMs=Math.round(performance.now()-current.started);state().history.push({id:crypto.randomUUID(),profile:profileKey(),at:new Date().toISOString(),type:q.type,target:q.target,firstTry:current.attempts===1,attempts:current.attempts,cueUsed:current.cueUsed,round:s.round,responseMs});if(state().history.length>700)state().history=state().history.slice(-700);s.lastTarget=q.target;s.cursor++;s.sessionCount++;await persist();const phrase=praiseFor(q.target,q.type),fb=$('#identifyFeedback');if(fb)fb.innerHTML="<b>✓ "+esc(phrase)+"</b>";if(p.celebration)celebrate?.(button);speak(phrase.replace('—',''));const limit=p.sessionLength==='continuous'?null:Number(p.sessionLength);nextTimer=setTimeout(()=>{if(limit&&s.sessionCount>=limit){sessionComplete(q.type);return}if(s.cursor>=s.deck.length){roundComplete(q.type);return}renderQuestion(q.type)},p.celebration?1050:720)}
  function roundComplete(type){const p=prefs(type),s=session(type);if(!s)return launch();if(p.sessionLength==='continuous'){refillRound(s,p);persist().then(()=>renderQuestion(type));return}document.body.classList.add('identify-active');main.innerHTML="<div class='identify-finish'><div class='identify-finish-icon'>★</div><span class='eyebrow'>ROUND COMPLETE</span><h1>You found every selected "+(type==='colours'?'colour':'shape')+"!</h1><p>Round "+s.round+" is complete.</p><div class='actions'><button class='btn' data-action='identifyAgain' data-identify-type='"+type+"'>Practise again</button><button class='btn secondary' data-action='identifyChooseNew' data-identify-type='"+type+"'>Change "+type+"</button><button class='btn ghost' data-action='identifyExit'>Done</button></div></div>";celebrate?.(null)}
  function sessionComplete(type){const s=session(type);document.body.classList.add('identify-active');main.innerHTML="<div class='identify-finish'><div class='identify-finish-icon'>✓</div><span class='eyebrow'>SESSION COMPLETE</span><h1>Great practice!</h1><p>You completed "+s.sessionCount+" questions. Your place in the selected set is saved.</p><div class='actions'><button class='btn' data-action='identifyContinue' data-identify-type='"+type+"'>Continue this set</button><button class='btn secondary' data-action='identifyChooseNew' data-identify-type='"+type+"'>Change "+type+"</button><button class='btn ghost' data-action='identifyExit'>Done</button></div></div>"}
  async function again(type){const p=prefs(type),s=session(type);if(!s)return config(type);s.sessionCount=0;refillRound(s,p);await persist();renderQuestion(type)}
  async function continueSet(type){const p=prefs(type),s=session(type);if(!s)return config(type);s.sessionCount=0;if(s.cursor>=s.deck.length)refillRound(s,p);await persist();renderQuestion(type)}
  async function restartSaved(type){const s=session(type),p=prefs(type);if(!s){toast('There is no saved set to restart.');return}if(!confirm('Restart this '+type+' set from the beginning? Recorded progress will stay in Communication Story.'))return;s.deck=makeDeck(p.selected,null);s.cursor=0;s.round=(s.round||0)+1;s.lastTarget=null;s.lastPos=null;s.posQueue=[];s.visualIndex++;s.sessionCount=0;await persist();if(modal.open)modal.close();renderQuestion(type)}
  function exit(){cleanup();if(modal.open)modal.close();go('practice')}
  function progressHTML(){const h=state().history.filter(x=>x.profile===profileKey()),now=Date.now(),recent=h.filter(x=>now-new Date(x.at).getTime()<=7*86400000);if(!recent.length)return '';const part=(rows,type)=>{if(!rows.length)return '';const ids=[...new Set(rows.map(x=>x.target))],first=rows.filter(x=>x.firstTry).length;return "<div class='identify-progress-part'><b>"+(type==='colours'?'🎨 Colours':'🔷 Shapes')+"</b><p>"+ids.map(id=>esc(label(type,id))).join(', ')+" practised this week.</p><small>"+first+" of "+rows.length+" recent opportunities were selected on the first try. This describes WAPS practice only; it is not a mastery or diagnostic score.</small></div>"};return "<section class='identify-progress-card'><div><span class='eyebrow'>COLOURS & SHAPES</span><h2>Recent identification practice</h2>"+part(recent.filter(x=>x.type==='colours'),'colours')+part(recent.filter(x=>x.type==='shapes'),'shapes')+"<button class='btn ghost' data-action='identifyLaunch'>Open Colours & Shapes</button></div></section>"}
  async function handleClick(el){const typeBtn=el.closest('[data-identify-type]'),tokenBtn=el.closest('[data-identify-token]'),presetBtn=el.closest('[data-identify-preset]'),choiceBtn=el.closest('[data-identify-choice]');if(choiceBtn){await choose(choiceBtn.dataset.identifyChoice,choiceBtn);return true}if(tokenBtn){toggleToken(tokenBtn.dataset.identifyToken,tokenBtn);return true}if(presetBtn){preset(presetBtn.dataset.identifyPreset);return true}const a=el.closest('[data-action]')?.dataset.action;if(typeBtn&&!['identifyAgain','identifyChooseNew','identifyContinue'].includes(a||'')){config(typeBtn.dataset.identifyType);return true}if(!a||!a.startsWith('identify'))return false;if(a==='identifyLaunch'){launch();return true}if(a==='identifyStart'){await start();return true}if(a==='identifyHear'){speakInstruction();return true}if(a==='identifyExit'){exit();return true}if(a==='identifyRestartSet'){await restartSaved(draft?.type||'colours');return true}if(a==='identifyAgain'){await again(typeBtn?.dataset.identifyType||'colours');return true}if(a==='identifyContinue'){await continueSet(typeBtn?.dataset.identifyType||'colours');return true}if(a==='identifyChooseNew'){cleanup();config(typeBtn?.dataset.identifyType||'colours');return true}return false}
  const validationErrors=validateIdentifyData();if(validationErrors.length)console.error('WAPS Colours & Shapes data validation',validationErrors);
  return {launch,handleClick,progressHTML,cleanup,validationErrors};
}
